#!/bin/sh

# Prints all batteries, their percentage remaining and an emoji corresponding
# to charge status (🔌 for plugged up, 🔋 for discharging on battery, etc.).
# Loop through all attached batteries and format the info

for battery in /sys/class/power_supply/BAT?*; do
	# If non-first battery, print a space separator.
	[ -n "${capacity+x}" ] && printf " "
	# Sets up the status and capacity
	capacity="$(cat "$battery/capacity" 2>&1)"
	case "$(cat "$battery/status" 2>&1)" in
		"Full") status="🔋" ;;
		"Discharging") status="";
     [ "$capacity" -le 20 ] && notify-send "Battery Low!" "Battery capacity only $capacity% remaining";;
		"Charging") status="⚡";
      [ "$capacity" -eq 99 ] && notify-send "Battery Full!";;
		"Not charging") status="🚫" ;;
		"Unknown") status="♻️ " ;;
		*) exit 1 ;;
	esac
	# Will make a warn variable if discharging and low
	[ "$status" = "" ] && [ "$capacity" -le 25 ] && warn="❗"
	# Prints the info
	printf "%s%s%d%%" "$status" "$warn" "$capacity"; unset warn
done && printf "\\n"
