#!/bin/bash
set -e

bluetoothctl power on
notify-send "scanning for bluetooth devices"
bluetoothctl --timeout 3 scan on

line=$(bluetoothctl devices | cut -b 8- | sed -e "s/ /|/" | dmenu -p "Choose Device: " -l 10)
mac=$(echo $line | cut -d'|' -f1)
name=$(echo $line | cut -d'|' -f2)

bluetoothctl pair $mac && notify-send "Paired with $name" || notify-send "Paring failed with $name"
bluetoothctl trust $mac || notify-send "Cannot trust $name" "failed to trust $mac" 
bluetoothctl connect $mac && notify-send "Connected with $name" || notify-send "Connection failed with $name"
