#!/bin/sh

backlight_location="/sys/class/backlight/intel_backlight"
EPSILON=100

if [ "$IS_THINKPAD" = "1" ]
then
  backlight_location="/sys/class/backlight/amdgpu_bl1"
  EPSILON=1000
fi

brightness_file="$backlight_location/brightness"
max_brightness="$(cat "$backlight_location/max_brightness")"
b=$(cat $brightness_file)

get() {
  echo "B-$(expr $b \* 100 / $max_brightness)%"
}

increment(){
  b=$(expr $EPSILON \* $1 \+ $b)
  if [ $b -gt $max_brightness ]
  then
    notify-send "Max brightness"
    exit 1
  else
    echo $b > $brightness_file
  fi
  pkill -RTMIN+11 dwmblocks
}

decrement(){
  if [ $b -eq 0 ]
  then
    notify-send "Min brightness"
    exit 1
  fi

  b=$(expr $b \- $1 \* $EPSILON)
  if [ $b -lt 0 ]
  then
    echo '0' > $brightness_file
  else
    echo $b > $brightness_file
  fi 
  pkill -RTMIN+11 dwmblocks
}

while getopts "g i: d:" flag
do
    case "${flag}" in
      g) get;;
      i) increment ${OPTARG};;
      d) decrement ${OPTARG};;
    esac
done
