#!/bin/sh

for i in $(echo $@ | sed -e "s/\.mp4//g"); do
  ffmpeg -i "$i.mp4" -c copy -bsf:v h264_mp4toannexb -f mpegts "$i.ts"
done

ffmpeg -i "concat:$(echo $@ | sed -e 's/mp4/ts/g' -e 's/\s/|/g')" -bsf:a aac_adtstoasc output.mp4
rm *.ts
