#!/bin/sh

ffmpeg -i "$1" -c copy -bsf:v h264_mp4toannexb -f mpegts /tmp/1.ts
ffmpeg -i "$2" -c copy -bsf:v h264_mp4toannexb -f mpegts /tmp/2.ts
ffmpeg -i "concat:/tmp/1.ts|/tmp/2.ts" -c:v copy -bsf:a aac_adtstoasc output.mp4
