#!/bin/sh
name=$(basename $1)
echo "creating $name"

echo "### creating ###" >> $HOME/.git-log
echo "name = $name" >> $HOME/.git-log
echo '' >> $HOME/.git-log

curl -X POST \
  -H "Authorization: token $(cat ~/.pat/git)" \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d '{"name":"'"$name"'"}' \
  https://api.github.com/user/repos

echo "CREATED REPO $name"
