#!/bin/sh

echo "target is $1"
echo 'start time'
read startDuration
echo 'end time'
read endDuration

ffmpeg -i $1 -ss $startDuration -t $endDuration -async 1 "swap.mp4"

cp $1 $HOME/tmp/swap.mp4
mv swap.mp4 $1
