#!/bin/sh

echo "target is $1"
echo 'start time'
read startDuration
echo 'end time'
read endDuration

ffmpeg -copyts -i $1 -ss $startDuration -to $endDuration -c copy "swap.mp4"

cp $1 $HOME/tmp/swap.mp4
mv swap.mp4 $1
