#!/bin/sh

ENCRYPTED="$HOME/private/diary.md.asc"
ENCRYPTED_COPY="/tmp/diary.copy.md.asc"
DECRYPTED="/tmp/diary.md"

cp $ENCRYPTED $ENCRYPTED_COPY
gpg --output $DECRYPTED --decrypt $ENCRYPTED
$EDITOR $DECRYPTED

printf "save>  "
read n

rm $ENCRYPTED
gpg --output $ENCRYPTED --encrypt --sign --armour -r ayushmantripathy2004@gmail.com $DECRYPTED

[ ! -f $ENCRYPTED ] && cp $ENCRYPTED_COPY $ENCRYPTED

shred $DECRYPTED
rm $DECRYPTED
