#!/bin/bash

musicDB="/mnt/chromeos/MyFiles/musicDB"

#download playlist
download_playlist () {
  echo 'downloading playlist'
  
  mkdir ~/download-tmp
  cd ~/download-tmp
 
  while read -r name; do
    read -r class
    read -r link

    echo "downloading $name"

    youtube-dlc -x --audio-format 'mp3' "$link"
    mv "./$(ls)" "$musicDB/$class/$name.mp3"
                     
  done < ~/playlist.txt
  rm -rf ~/download-tmp
}

#download music from yt
download_music (){
 
  printf "youtube link> "
  read link
  lang=$(find $musicDB -type d -printf '%f\n'| fzf)
  class=$(find $musicDB -maxdepth 1 -type f -printf '%f\n'| fzf)
  echo "class : $class"
  echo "language : $lang"
  printf 'Name Of Song> '
  read name
  name=${name// /_}
  
  mkdir ~/download-tmp
  cd ~/download-tmp
 
  #download
  youtube-dl -x --audio-format 'mp3' "$link"

  if [ $? -eq 0 ]; then
    # move from  temp dir
    mv "./$(ls)" "$musicDB/$lang/$name.mp3"
    echo "$lang/$name.mp3" >> "$musicDB/$class"
    echo "$lang/$name.mp3 $class $link" >> ~/playlist.txt
    echo "SUCCESS!"
  else
    echo "FAILED"
  fi
  
  rm -rf ~/download-tmp
}

if [[ $1 == '-r' ]]; then
  download_playlist
else
  download_music
fi
