#!/bin/bash

musicDB="$MUSICDB"

#download music from yt
download_music (){
  printf "youtube link> "
  read link
  lang=$(find $musicDB -type d -printf '%f\n'| fzf)
  class=$(find $musicDB -maxdepth 1 -type f -printf '%f\n'| fzf)
  echo "language : $lang"
  echo "class : $class"
  printf 'Name Of Song> '
  read name
  name=${name// /_}
  
  TMP_DOWNLOAD_LOCATION="/tmp/download-tmp"

  [ -d $TMP_DOWNLOAD_LOCATION ] || mkdir $TMP_DOWNLOAD_LOCATION
  [ -d "$TMP_DOWNLOAD_LOCATION/$name" ] || mkdir "$TMP_DOWNLOAD_LOCATION/$name"

  cd "$TMP_DOWNLOAD_LOCATION/$name"
 
  #download
  yt-dlp -x -f worst --audio-format 'mp3' "$link"

  if [ $? -eq 0 ]; then
    # move from  temp dir
    mv "./$(ls)" "$musicDB/$lang/$name.mp3"
    echo "$lang/$name.mp3" >> "$musicDB/$class"
    echo "$name.mp3 $class $lang $link" >> ~/playlist.txt
    echo "SUCCESS!"
  else
    echo "FAILED"
  fi
}

download_music
