#!/bin/bash

musicDB="$MUSICDB"

#download music from yt
download_music (){
  printf "youtube link> "
  read link
  lang=$(find $musicDB -type d -printf '%f\n'| fzf)
  class=$(find $musicDB -maxdepth 1 -type f -printf '%f\n'| fzf)
  echo "language : $lang"
  echo "class : $class"
  printf 'Name Of Song> '
  read name
  name=${name// /_}
  
  mkdir ~/download-tmp
  cd ~/download-tmp
 
  #download
  yt-dlp -x -f worst --audio-format 'mp3' "$link"

  if [ $? -eq 0 ]; then
    # move from  temp dir
    mv "./$(ls)" "$musicDB/$lang/$name.mp3"
    echo "$lang/$name.mp3" >> "$musicDB/$class"
    echo "$name.mp3 $class $lang $link" >> ~/playlist.txt
    echo "SUCCESS!"
  else
    echo "FAILED"
  fi
  
  rm -rf ~/download-tmp
}

if [[ $1 == '-m' ]]; then
  echo "not completed the script"
else
  download_music
fi
