#!/bin/sh

error() {
  echo "[ERROR] $1"
  exit
}

[ -f "./output.mp3" ] && error "output.mp3 already exits"

echo "Defaulting to 0th stream, use -s"

ffmpeg -i $1 -q:a 0 -map a ./output.mp3

echo "Generated ./output.mp3"
