#!/bin/bash

tmp_file="/tmp/bluetooth-deivce-info"
bluetoothctl info > $tmp_file

name=$(cat $tmp_file | grep -e "Name" | cut -b 8-)

#if [[ "$name" =~ ^$ ]]; then
#  echo "No"
#else 
#fi


if [[ -z "$name" ]]
then
 echo "🚫"
else
 battery=$(cat $tmp_file | grep -e "Battery Percentage" | grep -e "([0-9]*)" -o)
 echo "$name $battery"
fi
