#!/bin/sh

timestamp="../timestamps.txt"

echo "background image: $2"
echo "songs directory: $1"

cd "$1" || exit

rm songs.txt
for i in *
do
  echo $i >> songs.txt
done
$EDITOR songs.txt

printf "continue? "
read -r null

time="0"
rm $timestamp
for i in $(cat songs.txt) 
do
  echo "$(date -d@$time -u +%H:%M:%S) $i" | sed -e "s/_/ /g" -e "s/\..*$//" >> $timestamp
  duration=$(ffprobe -i $i -show_entries format=duration -v quiet -of csv="p=0" | sed -e 's/\..*$//')
  time=$(expr $duration \+ $time)
done

concatvideo $(cat songs.txt)

mv output.mp4 ../audio.mp4
rm songs.txt

cd ..

# Generating Video Background
duration=$(ffprobe -i audio.mp4 -show_entries format=duration -v quiet -of csv="p=0")
count=$(echo "console.log(Math.ceil(Math.log10($duration)) - 1)" | node)

vids_names="vids.txt"
echo "file clip.mp4" > $vids_names 
for i in $(seq 9)
do
  echo "file clip.mp4" >> $vids_names
done

ffmpeg -loop 1 -i $2 -t 10 -pix_fmt yuv420p -vf scale=1920:1080 clip.mp4

for i in $(seq $count)
do
  ffmpeg -f concat -i vids.txt -c copy tmp.mp4
  mv tmp.mp4 clip.mp4
done
rm $vids_names

# Generating Final Video
ffmpeg -i clip.mp4 -i audio.mp4 -map 0:v -map 1:a -c copy -shortest final.mp4

rm clip.mp4
rm audio.mp4
