#!/bin/bash

[ ! -f pics.txt ] && echo "pics.txt required"

# pics.txt
# file "name.jpg"
# duration 1

# matching song

[ ! -f music.ogg ] && echo "music.ogg required"

ffmpeg -f concat -safe 0 -i pics.txt -i music.ogg -vf "scale=min(iw\,1920):min(ih\,1080):force_original_aspect_ratio=decrease,pad=1920:1080:(1920-iw)/2:(1080-ih)/2:black" -c:v libx264 -crf 18 -r 30 -shortest -y ./out.mp4
