#!/bin/bash

# pics.txt
# file "name.jpg"
# duration 1

file_error() {
  echo "Format for pics.txt"
  echo 'file name.jpg'
  echo 'duration 1'
  exit
}

if [ $# -lt 2 ];
then
  echo "Usage <command> pics.txt music.mp4"
  file_error
fi

# landscape

echo "Example: 1920x1080"
printf "Enter height: "
read h
printf "Enter Width: "
read w

ffmpeg -f concat -safe 0 -i pics.txt -i music.ogg -vf "scale=min(iw\,$w):min(ih\,$h):force_original_aspect_ratio=decrease,pad=$w:$h:($w-iw)/2:($h-ih)/2:black" -c:v libx264 -crf 18 -r 30 -shortest -y ./out.mp4
