#!/bin/sh
name=$(basename "$1")

echo "repo name is '$name'"
printf "Name of base branch? (release) "
read -r base_branch
printf "Name of head to merge? (master) "
read -r head_branch
printf "Commit Message> "
read -r commit_msg

echo "merging $head_branch --> $base_branch in $name"
printf "confirm? "
read null

curl \
  -X POST \
  -u "$GITHUB_USERNAME":$(cat "$HOME/private/.pat/$GITHUB_USERNAME") \
  -H "Accept: application/vnd.github.v3+json" \
  "https://api.github.com/repos/$GITHUB_USERNAME/$name/merges" \
  -d "{\"base\":\"$base_branch\",\"head\":\"$head_branch\", \"commit_message\": \"$commit_msg\"}"

if [ $? = "0" ]; then
  echo "Merge sucessfully"
else
  echo "Merge Failed!!!!"
fi
