#!/bin/sh
music_db='/mnt/chromeos/MyFiles/musicDB/'

startPlaylist(){
  mocp -S

  mocp -c
  # suffle and repeat mode
  mocp -t s

  list=""
  for name in $(cat "$music_db/$1.txt")
  do
    list="$list $music_db$name"
  done
  mocp -a $list
  mocp -p -t r -v 50 
}

startAll(){
  mocp -S
  mocp -c

  mocp -a "$music_db/"

  mocp -t s
  mocp -p -t r -v 50
}

while getopts "p s: a x n v:" flag
do
    case "${flag}" in
        p) mocp -G;;
        s) startPlaylist ${OPTARG};;
        a) startAll;;
        v) mocp -v ${OPTARG};;
        x) mocp -x;;
        n) mocp -f;;
    esac
done
