#!/bin/sh
music_db="$MUSICDB"

startServer(){
  mocp -S
  mocp -c
  mocp -t s
  mocp -t r -v 50
}

addEverySong(){
  mocp -a "$music_db"
}

addPlaylist(){
  list=""
  for name in $(cat "$music_db/$1.txt")
  do
    list="$list $music_db/$name"
  done
  mocp -a $list
  mocp -p
}

addLang(){
  list=""
  for name in $(ls -1 "$MUSICDB/$1")
  do
    mocp -a "$music_db/$1/$name"
  done
  mocp -p
}

findSong(){
  name=$(find $music_db -type f | fzf)
  mocp -c
  mocp -a "$name"
  mocp -p
}

while getopts "s a: l: p v: x n c d:" flag
do
    case "${flag}" in
        s) startServer;;
        a) addPlaylist ${OPTARG};;
        l) addLang ${OPTARG};;
        e) addEverySong;;
        f) findSong;;
        p) mocp -G;;
        v) mocp -v ${OPTARG};;
        x) mocp -x;;
        n) mocp -f;;
        c) mocp -c;;
        d) music_db=${OPTARG};;
    esac
done
