#!/bin/bash

open(){

  if [[ $2 == "-v" ]]; then
    vim $1

  elif  [[ $2 == '-c' ]]; then
    cat $1

  elif  [[ $1 == *".mp"* ]]; then
    mocp -S
    mocp -a $1  -p -t r -v 90

  elif  [[ $1 == *".m3u" ]]; then
    mocp -S
    mocp -c
    mocp -a $1 -p -t r -v 90

  elif  [[ $1 == *".js" ]]; then
    vim $1

  elif  [[ $1 == *".json" ]]; then
    vim $1

  elif  [[ $1 == *".txt" ]]; then
    vim $1

  elif  [[ $1 == *"/."* ]]; then
    vim $1

  else
    xdg-open $1
  fi
}

findfzf(){
open $(sudo find $1 -type f -name "*" ! -path "*/.cache/*" ! -path "*/node_modules*/*" ! -path "*/.git/*" ! -path '*/.fzf/*' ! -path '*/.npm/*' ! -path '*/.codeintel/*' ! -path "*/share/*" | fzf) $2
}

if  [[ $1 == / ]]; then
  open $(sudo find / -type f | fzf) $1

elif [[ $1 == '-l' ]]; then
  xdg-open "https://$2"

elif [[ $1 == '-c' ]]; then
  xdg-open "https://$2.com"

elif  [[ $1 == . ]]; then
  findfzf . $1

elif  [[ $1 == '-a' ]]; then
  open $(sudo find ~ | fzf) $1

else
  findfzf ~ $1
fi
