#!/bin/sh

GREEN='\033[1;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color
echo "${GREEN}PRODUCTIVITY RATIO${NC}"

PR_DATA="/home/ayushmantripathy2004//pr_data.txt"
LAST_LINE=$(tail $PR_DATA -n 1)

# score pr days acc_score date
acc_score=$(echo $LAST_LINE | cut -d ' ' -f 4)
day_count=$(echo $LAST_LINE | cut -d ' ' -f  3)

echo "PR  (0,8]          | ${YELLOW}$(echo $LAST_LINE | cut -d ' ' -f 2)${NC}"
echo "current accumulate | $acc_score"
echo "day count          | $day_count"

printf "|> "; read op
printf "morning sessions [8:12]> "; read s1
printf "afternoon session [2:3]> "; read s2
printf "evening session [5:7]> "; read s3
printf "night session [9:1]> "; read s4

score=$(expr $s1 + $s2 + $s3 + $s4)
echo "yesterday's | $(echo $LAST_LINE | cut -d ' ' -f 1)\ntoday       | $score"

day_count=$(expr $day_count + 1)
acc_score=$(expr $acc_score + $score)
pr=$(echo | awk -v a="$acc_score" -v b="$day_count" 'BEGIN { printf "%0.2f\n", (a/b) }')
echo "current pr  | ${YELLOW}$pr${NC}"
printf "save [?]>"; read op
echo "$score $pr $day_count $acc_score $(date +%d/%m/%g)" >> $PR_DATA
