#!/bin/sh
name=$(basename $1)
printf "delete repo $name? "
read NULL

curl \
  -X DELETE \
  -H "Accept: application/vnd.github.v3+json" \
  -H "Authorization: token $(cat ~/private/.pat/$GITHUB_USERNAME)" \
  "https://api.github.com/repos/$GITHUB_USERNAME/$name"
