#!/bin/sh
name=$(basename $1)
echo "deleting $name"

curl \
  -X DELETE \
  -H "Accept: application/vnd.github.v3+json" \
  -H "Authorization: token $(cat ~/.pat/git)" \
   "https://api.github.com/repos/AyushmanTripathy/$name"
