#!/bin/sh

clipboard="$HOME/tmp/clipboard.txt"

while getopts "s" flag
do
    case "${flag}" in
        s) echo "$(xclip -o)\n" >> $clipboard && exit;;
    esac
done

line=$(cat $clipboard | dmenu -p "Select: " -l 10)
echo "$line" | sed -e 's/\\n//' | xclip -selection clipboard
