#!/bin/sh

clipsdir="/tmp/clipsdir"

if [ ! -d $clipsdir ]; then
  mkdir $clipsdir
  echo "0" > "$clipsdir/id"
fi

saveClip() {
  expr "$(cat $clipsdir/id)" + 1 > "$clipsdir/id"
  unique_id=$(cat $clipsdir/id)
  time_id=$(date '+%H-%M-%S')
  xclip -sel clipboard -o > "$clipsdir/$unique_id|  $time_id"
  notify-send "saved clipboard as $unique_id"
  exit
}

while getopts "s" flag
do
    case "${flag}" in
        s) saveClip;;
    esac
done


line=$(ls $clipsdir | sed -e "/id/d" | sort -r | dmenu -p "Select: " -l 10)
cat "$clipsdir/$line" | xclip -selection clipboard
