#!/bin/sh

prefix=".."
playlist="./playlists"

mkdir $playlist

for file in $(ls *.txt)
do
  name=$(echo $file | sed -e "s/\.txt//")
  file_name="$playlist/$name.m3u"

  echo "#EXTM3U" >> $file_name
  echo "#PLAYLIST: $name" >> $file_name

  for entry in $(cat $file)
  do
    echo "$prefix/$entry" >> $file_name
  done
done
