#!/bin/sh

if [ $# -eq 0 ]
then
  username="$GITHUB_USERNAME"
else
  username="$1"
fi

git remote set-url origin \
"https://pat:$(cat ~/private/.pat/$username)@github.com/$username/$(basename "$PWD").git"
