#!/bin/sh

username="$GITHUB_USERNAME"
token="$GITHUB_USERNAME"

while getopts "u: t:" flag
do
    case "${flag}" in
        u) username="${OPTARG}";;
        t) token="${OPTARG}";;
        *) echo "unknown option";;
    esac
done

git remote set-url origin \
"https://$(cat ~/private/.pat/$token)@github.com/$username/$(basename "$PWD").git"
