#!/bin/bash 

open(){
  read input
  xdg-open "$1${input// /$2}"
}

openfzf(){ 
  cd
  name=$(find -maxdepth 1 -type d | fzf)
  xdg-open "$1${name//./}"
}

while getopts "w g r y s o" opt

do
  case "${opt}" in
    g) openfzf "https://github.com/$GITHUB_USERNAME";;
    r) open "https://www.reddit.com/r/" '+';;
    y) open "https://www.youtube.com/results?search_query=" '+';;
    s) open "https://www.google.com/search?q=" '+';;
    o) open "https://" '_';;
    w) open "https://en.wikipedia.org/wiki/" '_';;
    esac
done
