#!/bin/sh

file="$HOME/private/wifi_passwords.txt"

notify-send "Scanning for networks"
SSID=$(nmcli -f SSID device wifi list --rescan yes | sed -n '1!p' | dmenu -p "Select Wifi: " -l 10 | sed 's/\s*$//')
password=$(grep -e "$SSID" $file)

if [[ ! -z "$password" ]]
then
  password=$(echo $password | cut -d'|' -f2)
else
  password=$(echo '' | dmenu -p "Enter Password: ")
  echo "$SSID|$password" >> $file
fi

echo "$SSID $password"
nmcli device wifi connect "$SSID" password "$password"
if [ $? -eq 0 ]
then
  notify-send "Connected with $SSID"
else 
  notify-send "Failed to Connect with $SSID" "password: $password"
fi
