#!/bin/sh

file="$HOME/private/wifi_passwords.txt"

notify-send "Scanning for networks"
line=$(nmcli device wifi list --rescan yes | sed -n '1!p' | cut -b 9- | dmenu -p "Select Wifi: " -l 10)
BSSID=$(echo $line | cut -d' ' -f1)
SSID=$(echo $line | cut -d' ' -f2)
password=$(grep -e "$BSSID" $file)

if [[ ! -z "$password" ]]
then
  password=$(echo $password | cut -d'|' -f2)
else
  password=$(echo '' | dmenu -p "Enter Password: ")
  echo "$BSSID|$password" >> $file
fi

nmcli device wifi connect "$BSSID" password "$password"
if [ $? -eq 0 ]
then
  notify-send "Connection Established with $SSID"
else 
  notify-send "Failed to Connect with $BSSID" "Tried to connect with $SSID [password: $password]"
fi
